server:
  port: 15789
nga:
  stock:
    - tid: 24929430
      name: 主楼
    - tid: 24929177
      name: 乔帮专楼
    - tid: 24913158
      name: 牛神专楼
    - tid: 24900465
      name: 禾戈专楼
    - tid: 24906978
      name: 白博专楼
  api:
    url: http://ngabbs.com/app_api.php?__lib=post&__act=list
  dingding:
    url: 
  author:
    - uid: 27178316
      name: gxgujnk1993
    - uid: 38666451
      name: 泰莫拉尔
    - uid: 100921
      name: barryking
    - uid: 42255599
      name: 天之藍～
    - uid: 533348
      name: colaman2006
    - uid: 60002731
      name: qiaoxuejia
    - uid: 4627122
      name: 牛中牛神
    - uid: 150058
      name: 阿狼
    - uid: 5254815
      name: 禾戈禾戈
    - uid: 1904077
      name: 白博士acbogeh